### ISSUE TITLE
Division operator is not working properly.

### ISSUE THREAD

**Issue by algoramming** [sabikrahat/bangla_handwritten_math_solver#3]
Have tried in the canvas ১২ ÷ ২ ।  It Shows me ১২ - ৯৯২ :  -৯৮০

![image](https://user-images.githubusercontent.com/81485175/200151612-9528a2bb-52cc-4be2-9f12-9d0dd7f374b8.png)

![9_system_prediction](https://user-images.githubusercontent.com/81485175/200151656-e6df5f1f-d9d5-4e32-90d9-ade36f031667.jpg)

**Comment by sabikrahat** [comment]
There is an issue in detecting `[÷]` operator. The individual 3 part of that `[÷]` operator detect individually. For that reason we have change the division operator from `[÷]` to `[/] `sign. You can try with this action. 

`Moreover, I'm still working on it to detect division sign of that [÷] view.`

![image](https://user-images.githubusercontent.com/49031412/200151826-ce23b2a4-8b70-47bd-ac62-aa7d8c8fd024.png)
